auth:
  registry.hub.docker.com:
    username: USERNAME
    password: PASSWORD
images:
  k8s.gcr.io/sig-storage/csi-attacher: henjue/csi-attacher
  k8s.gcr.io/sig-storage/csi-snapshotter: henjue/csi-snapshotter
  k8s.gcr.io/sig-storage/csi-provisioner: henjue/csi-provisioner
  k8s.gcr.io/sig-storage/csi-resizer: henjue/csi-resizer
  k8s.gcr.io/sig-storage/csi-node-driver-registrar: henjue/csi-node-driver-registrar

